package com.matiasdev.elecapp.features.inspections.domain

import java.time.Instant

data class PillarInspection(
    val inspectionId: String,
    val reviewStatus: InspectionSectionReviewStatus,
    val exists: Boolean?,
    val propertyType: PropertyType?,
    val propertyTypeOther: String?,
    val supplyType: SupplyType?,
    val accessible: AccessStatus,
    val generalCondition: GeneralCondition,
    val mainBreakerPresent: YesNoUnknown,
    val mainBreakerAmps: Int?,
    val mainBreakerOtherAmps: Int?,
    val differentialPresent: YesNoUnknown,
    val differentialRatedAmps: Int?,
    val differentialOtherRatedAmps: Int?,
    val differentialSensitivityMa: Int?,
    val differentialOtherSensitivityMa: Int?,
    val differentialTestResult: DifferentialTestResult,
    val conductorSectionMm2: Double?,
    val conductorOtherSectionMm2: Double?,
    val conductorMaterial: ConductorMaterial,
    val conductorMaterialOther: String?,
    val conductorCondition: ConductorCondition,
    val neutralIdentified: YesNoUnknown,
    val groundingVisible: YesNoUnknown,
    val protectionCompatibility: ProtectionCompatibility,
    val protectionCompatibilityNotes: String?,
    val notes: String?,
    val createdAt: Instant,
    val updatedAt: Instant,
)
