package com.matiasdev.elecapp.features.electricaltools.domain.diagrams

import com.matiasdev.elecapp.features.electricaltools.domain.ComponentTerminal
import com.matiasdev.elecapp.features.electricaltools.domain.DiagramType
import com.matiasdev.elecapp.features.electricaltools.domain.ElectricalDiagram
import com.matiasdev.elecapp.features.electricaltools.domain.WiringConnectionStep

val threeWaySwitchDiagram = ElectricalDiagram(
    id = "teclas-combinadas-escalera",
    type = DiagramType.THREE_WAY_SWITCH,
    title = "Llaves Combinadas (Simple y Doble Inversora)",
    subtitle = "Circuito de combinación simple (escalera) y doble inversora / cruzamiento (4 vías) con simbología.",
    category = "Instalación Domiciliaria",
    badgeText = "220V AC",
    requiredVoltage = "220 Vca",
    safetyVoltageNote = "Circuito normalizado por retorno seguro (Fase al centro, Neutro a la lámpara).",
    requiredComponents = listOf(
        "2 llaves de combinación simples (3 bornes / 1 punto combinación)",
        "1 o más llaves de combinación doble o doble inversora / 4 vías (para 3 o más lugares de encendido)",
        "Luminarias en paralelo (con neutro y retorno común)",
        "Conductores normalizados de 1,5 mm² (Fase Marrón, Neutro Celeste, Retorno Rojo/Naranja, Auxiliares Marrón/Gris y Tierra Verde)",
    ),
    terminalLegend = listOf(
        ComponentTerminal("Borne Central (Común)", "Común de Llave Combinada 1", "Recibe la FASE permanente (Marrón)."),
        ComponentTerminal("Bornes Laterales (1 y 2)", "Auxiliares / Viajeros", "2 cables que unen las llaves entre sí pasando por las cajas de paso."),
        ComponentTerminal("Borne Central (Común)", "Común de Llave Combinada 2", "Envía el RETORNO (Naranja / Rojo) a las luminarias."),
        ComponentTerminal("Doble Inversora (4 bornes)", "Cruzamiento Intermedio", "Conmutación interna en 'X' para invertir el cruce de los auxiliares."),
    ),
    stepByStepGuide = listOf(
        WiringConnectionStep(
            stepNumber = 1,
            title = "Fase al Común de la Llave 1",
            wireName = "Fase (Castaño / Marrón)",
            wireColorHex = 0xFF795548,
            fromTerminal = "Línea general de Fase",
            toTerminal = "Borne Central (Común) de Llave Combinada 1",
            description = "Llevar la fase de alimentación únicamente al borne central de la primera llave.",
        ),
        WiringConnectionStep(
            stepNumber = 2,
            title = "Tendido de Cables Auxiliares (Viajeros)",
            wireName = "Auxiliares (Marrón / Gris)",
            wireColorHex = 0xFF9E9E9E,
            fromTerminal = "Bornes laterales de Llave Combinada 1",
            toTerminal = "Bornes de entrada de Llave Doble Inversora (o Llave Combinada 2)",
            description = "Tirar 2 cables auxiliares entre las llaves.",
        ),
        WiringConnectionStep(
            stepNumber = 3,
            title = "Intercalado de Llave Doble Inversora (4 Vías)",
            wireName = "Puentes auxiliares",
            wireColorHex = 0xFFFF9800,
            fromTerminal = "Salida Llave Doble Inversora",
            toTerminal = "Bornes laterales de la siguiente Llave Combinada",
            description = "Para encender desde 3 o más lugares, intercalar llaves doble inversoras en el camino de los auxiliares.",
        ),
        WiringConnectionStep(
            stepNumber = 4,
            title = "Retorno desde la última Llave a las Luminarias",
            wireName = "Retorno de luz (Naranja / Rojo)",
            wireColorHex = 0xFFE65100,
            fromTerminal = "Borne Central (Común) de la última Llave",
            toTerminal = "Línea común de Retorno de todas las lámparas",
            description = "Del común de la última llave sale el retorno hacia el contacto central de las luminarias conectadas en paralelo.",
        ),
        WiringConnectionStep(
            stepNumber = 5,
            title = "Neutro y Puesta a Tierra directos",
            wireName = "Neutro (Celeste) y Tierra (Verde)",
            wireColorHex = 0xFF03A9F4,
            fromTerminal = "Troncal de Neutro y Tierra",
            toTerminal = "Casquillos de lámparas y chasis de cajas metálicas",
            description = "El neutro va directo a las luminarias y la tierra a todas las cajas y portalámparas.",
        ),
    ),
    practicalTips = listOf(
        "PROHIBIDO EL MÉTODO DE CORTOCIRCUITO: El método que lleva Fase y Neutro a cada llave está PROHIBIDO por la AEA debido al riesgo de cortocircuito franco y electrificación del casquillo.",
        "SIMBOLOGÍA DE PLANO: En planos unifilares, la llave combinada simple se dibuja como un círculo con palanca diagonal quebrada, y la llave de cruzamiento como un círculo con 4 patitas en X.",
        "LUMINARIAS EN PARALELO: Si se controlan varias lámparas a la vez, todas se conectan en paralelo entre la línea de Retorno y la línea de Neutro.",
    ),
    securityWarning = "La sección mínima de conductores para iluminación es de 1,5 mm² de cobre según AEA 771.",
    aeaReference = "AEA 90364-7-771.12 y 771.19 (Circuitos de iluminación y combinación).",
)

val waterPumpDiagram = ElectricalDiagram(
    id = "tanque-cisterna-tablero-12v",
    type = DiagramType.WATER_PUMP_TANK_CISTERN,
    title = "Tablero de Bomba: Tanque y Cisterna (12V / 24V MBTS)",
    subtitle = "Automatización completa con contactor, guardamotor, selectora Manual-0-Auto y flotantes en Muy Baja Tensión de Seguridad.",
    category = "Fuerza Motriz y Automatización",
    badgeText = "Seguridad 12V",
    requiredVoltage = "Potencia 220V / Comando 12Vca o 24Vca",
    safetyVoltageNote = "Comando de flotantes en MBTS (12Vca/24Vca) para evitar riesgo letal de electrocución en el agua.",
    requiredComponents = listOf(
        "Interruptor termomagnético bipolar de cabecera",
        "Interruptor diferencial (Disyuntor 30 mA)",
        "Contactor tripolar o bipolar con bobina de 12Vca o 24Vca",
        "Relé térmico o Guardamotor calibrado a la corriente nominal de la bomba (In)",
        "Transformador de seguridad 220V / 12Vca o 24Vca (mínimo 50VA / 100VA) con aislación galvánica",
        "Llave selectora de 3 posiciones fijas (MANUAL - 0 - AUTOMÁTICO)",
        "2 interruptores flotantes de nivel herméticos (1 para Cisterna + 1 para Tanque superior)",
        "Luces testigo LED para tablero: Verde (Marcha), Roja (Falta de agua), Ámbar (Falla térmica)",
        "Gabinete estanco para tablero (IP54 / IP65)",
    ),
    terminalLegend = listOf(
        ComponentTerminal("220V Fuerza", "Entrada de Potencia", "L1-N que alimentan la bomba a través del contactor y relé térmico."),
        ComponentTerminal("Trafo 12Vca", "Fuente MBTS", "Transformador que genera los 12V o 24V seguros para los flotantes de nivel."),
        ComponentTerminal("Bobina A1-A2", "Bobina del Contactor", "Acciona los contactos de potencia. Trabaja en 12V o 24V según el transformador."),
        ComponentTerminal("Flotante Cisterna", "Contacto de Seguridad", "Contacto NORMAL ABIERTO (NA) en reposo que se cierra con el flotante hacia arriba (con agua). Si no hay agua se abre y corta la bomba."),
        ComponentTerminal("Flotante Tanque", "Contacto de Llenado", "Contacto NORMAL CERRADO (NC) en reposo que se cierra cuando el tanque se vacía y pide agua. Al llenarse y flotar, se abre y detiene la bomba."),
        ComponentTerminal("Relé Térmico 95-96", "Contacto NC de Protección", "Corta el circuito de 12V a la bobina del contactor si el motor sufre sobrecarga térmica o se traba."),
        ComponentTerminal("Relé Térmico 97-98", "Contacto NA de Alarma", "Enciende la luz testigo ámbar de sobrecarga si dispara la protección térmica."),
        ComponentTerminal("Contactor 13-14", "Contacto NA Auxiliar", "Enciende la luz testigo verde de bomba en marcha."),
    ),
    stepByStepGuide = listOf(
        WiringConnectionStep(
            stepNumber = 1,
            title = "Circuito de Fuerza (220V)",
            wireName = "Fase y Neutro 2,5 mm²",
            wireColorHex = 0xFF795548,
            fromTerminal = "Térmica general -> Disyuntor",
            toTerminal = "Bornes 1 y 3 del Contactor -> Relé Térmico -> Motor Bomba",
            description = "Conectar la alimentación de 220V pasando por los contactos principales del contactor y del relé térmico directo a la bornera de la bomba.",
        ),
        WiringConnectionStep(
            stepNumber = 2,
            title = "Alimentación del Transformador de Seguridad",
            wireName = "Primario 220V (1,5 mm²)",
            wireColorHex = 0xFF03A9F4,
            fromTerminal = "Salida del Disyuntor 220V",
            toTerminal = "Bornes primarios (0-220V) del Transformador",
            description = "Alimentar el primario del transformador de 12V/24V protegido con fusible de 0,5A o termomagnética de comando.",
        ),
        WiringConnectionStep(
            stepNumber = 3,
            title = "Común de 12V a la Selectora",
            wireName = "Comando 12V (Violeta / Naranja)",
            wireColorHex = 0xFF9C27B0,
            fromTerminal = "Borne secundario (12V) del Transformador",
            toTerminal = "Borne central de la Llave Selectora (Man - 0 - Auto)",
            description = "Llevar la salida de 12V segura a la llave selectora de 3 posiciones en el frente del tablero.",
        ),
        WiringConnectionStep(
            stepNumber = 4,
            title = "Posición MANUAL (12V directo)",
            wireName = "Comando Manual 12V",
            wireColorHex = 0xFF4CAF50,
            fromTerminal = "Salida posición MANUAL de la selectora",
            toTerminal = "Borne 95 del relé térmico -> Borne A1 del contactor",
            description = "En modo manual la bomba arranca forzadamente para pruebas o vaciado, sin pasar por los flotantes pero siempre protegida por el relé térmico.",
        ),
        WiringConnectionStep(
            stepNumber = 5,
            title = "Posición AUTOMÁTICO (Flotantes en serie)",
            wireName = "Línea de flotantes 12V",
            wireColorHex = 0xFFFF9800,
            fromTerminal = "Salida posición AUTO de la selectora",
            toTerminal = "Flotante Cisterna -> Flotante Tanque -> Borne 95 Relé -> Borne A1",
            description = "En modo automático, la corriente de 12V debe pasar PRIMERO por el flotante de Cisterna (habilita si hay agua) y LUEGO por el flotante de Tanque (pide agua por bajo nivel) antes de llegar a la bobina A1 del contactor.",
        ),
        WiringConnectionStep(
            stepNumber = 6,
            title = "Retorno de 12V a Borne A2 de la Bobina",
            wireName = "Retorno 0V / Masa 12V",
            wireColorHex = 0xFF607D8B,
            fromTerminal = "Borne A2 del contactor",
            toTerminal = "Borne secundario (0V) del Transformador",
            description = "Cerrar el circuito de comando llevando el borne A2 de la bobina del contactor al borne 0V del secundario del transformador.",
        ),
        WiringConnectionStep(
            stepNumber = 7,
            title = "Conexión de Señalización y Luces Testigo",
            wireName = "Pilotos luminosos",
            wireColorHex = 0xFFFFEB3B,
            fromTerminal = "Contactos auxiliares (13-14 Contactor / 97-98 Relé / Flotante)",
            toTerminal = "Ojos de buey / Lámparas testigo del frente",
            description = "Verde = Marcha (vía 13-14), Ámbar = Sobrecarga térmica (vía 97-98), Roja = Cisterna vacía (vía contacto inverso de cisterna).",
        ),
    ),
    practicalTips = listOf(
        "POR QUÉ NUNCA USAR 220V EN FLOTANTES: El agua es altamente conductora. Los cables sumergidos sufren movimiento continuo, humedad y cloración. Si ingresa 220V a un flotante pinchado, toda la instalación sanitaria (grifos, duchas, tanque) queda electrificada con riesgo letal. La AEA exige MBTS (≤ 24V).",
        "Regulación del contrapeso: En la cisterna, el contrapeso debe ubicarse a 15-20 cm del cuerpo del flotante para asegurar que corte antes de que la bomba succione aire o sedimentos del fondo.",
        "Calibración del relé térmico: Ajustar el dial del relé térmico exactamente a la corriente nominal de la placa del motor (ej. para motor 0,75 HP ~ 4,2 A en 220V).",
        "Prueba de flotantes: Para probar el tanque superior, levantar el flotante con la mano (debe apagar la bomba) y soltarlo hacia abajo (debe pedir agua y activar el contactor).",
    ),
    securityWarning = "Toda la carcasa del motor de la bomba y las partes metálicas del tablero deben estar obligatoriamente conectadas a la jabalina de puesta a tierra (PE).",
    aeaReference = "Reglamentación AEA 90364-7-771.18 (Instalaciones de Fuerza Motriz y MBTS en tanques de reserva y cisternas).",
)
